# sensors.yaml
- platform: time_date
  display_options:
    - "time"
    - "date"

- platform: rest
  name: "prayer_times"
  unique_id: prayer_times
  json_attributes:
    - data
  # Replace <LATITUDE> and <LONGITUDE> with your actual coordinates
  resource: "https://api.aladhan.com/v1/timings?latitude=<LATITUDE>&longitude=<LONGITUDE>&method=5&school=2"
  value_template: '{{ value_json["data"]["meta"]["method"]["name"].title() }}'
  scan_interval: 3600
